###
POST  http://localhost:3003/login
Content-Type: application/json

{
     "email": "jana@gmail.com",
     "password": "1"
}


###
POST http://localhost:3003/login
Content-Type: application/json

{
     "email": "jana@gmail.com",
     "password": "1"
}

###
GET  http://localhost:3003/test HTTP/1.1
Content-Type: application/xml
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc
###
GET  http://localhost:3003/story/all 


###
GET  http://localhost:3003/post/2

###
PUT  http://localhost:3003/post/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc

{
     "text": "Teste", 
     "price": 200, 
     "accommodation": ""
}

###
PUT  http://localhost:3003/post/1?like=1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc

###
PUT  http://localhost:3003/post/comment1/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc

{
     "text": "textasdasdsa"
}

###
PUT  http://localhost:3003/post/comment2/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc

{
     "text": "TESTE 22"
}

###
PUT  http://localhost:3003/post/comment3/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc

{
     "text": "TESTE 33"
}


###
PUT  http://localhost:3003/post/comment1/1/like?like=-1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc


###
PUT  http://localhost:3003/post/comment2/1/like?like=-1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc

###
PUT  http://localhost:3003/post/comment3/1/like?like=-1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNjg4OTc3LCJleHAiOjE3MDkwODg5Nzd9.shCI1JDrHAxfFMmN78idGWWzCvGxFrTsh3FxQTFkyWc

###
GET  http://localhost:3003/post/comment1/1

###
GET http://localhost:3003/post/all
###
GET http://localhost:3003/video/all
###
GET http://localhost:3003/story/all

###
PUT http://localhost:3003/video/comment1/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTgsImlhdCI6MTYyMjk0MDMxNCwiZXhwIjoxNzA5MzQwMzE0fQ.naLPOf8WWoY2CXv3SvaIh9q3284y95y8qHI6Bcf3AJU

{
     "text": "TESTE 33"
}
